### ISSUE TITLE
Is the ESP32-S3 ELF up to date?

### ISSUE THREAD

**Issue by urish** [espressif/esp-rom-elfs#2]
I see a different version string in the ELF file v.s. the actual ROM in an ESP32-S3 production chip:

ELF: esp32s3-20200522  
Chip: esp32s3-20210327

Does the provided ELF file belong to an older chip revision?

**Comment by Lapshin** [comment]
@urish thank you for reporting this issue.

Could you please run `esptool.py chip_id` and post the output here?

**Comment by urish** [comment]
I'm currently traveling, so I won't have access to the physical chip for the next 2 weeks. I can post the ROM dump here if it helps

**Comment by Lapshin** [comment]
@urish , no thanks, I already have this. Have a good trip :)

**Comment by Lapshin** [comment]
@urish , the wrong rom for esp32s3 was released. Please use the last release from https://github.com/espressif/esp-rom-elfs/releases

Thank you for finding it!

**Comment by urish** [comment]
The updated version looks good, thanks!
