### ISSUE TITLE
Could debug info be included in the ROM ELFs?

### ISSUE THREAD

**Issue by noahp** [espressif/esp-rom-elfs#3]
I noticed the ROM ELFs do not contain any debug info. Would it be possible to provide ELFs with debug info?

```bash
>>> info address crc32_le                                                                                 │
Symbol "crc32_le" is at 0x40000628 in a file compiled without debugging.
```

**Comment by Lapshin** [comment]
@noahp , please see related discussion here https://github.com/espressif/esp-rom-elfs/pull/1#discussion_r949886357

**Comment by noahp** [comment]
Thanks, that makes sense! closing this request.
